// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

// const awsmobile = {
//   'aws_appsync_graphqlEndpoint': 'https://aaiacvhtirajlnci33aamrwkxy.appsync-api.ap-northeast-1.amazonaws.com/graphql',
//   'aws_appsync_region': 'ap-northeast-1',
//   'aws_appsync_authenticationType': 'API_KEY',
//   'aws_appsync_apiKey': 'da2-3gxozijn55gadoylwnbix4pbpq',
// };

// export default awsmobile;
import { config as dotenvConfig } from 'dotenv';
dotenvConfig();
const config = {
    aws_appsync_host: process.env.AWS_APPSYNC_HOST as string,
    aws_appsync_region: process.env.AWS_APPSYNC_REGION as string,
    aws_appsync_path: '/graphql',
    aws_appsync_endpoint: '',
    aws_appsync_apiKey: process.env.AWS_APPSYNC_APIKEY as string
};
config.aws_appsync_endpoint = config.aws_appsync_host + config.aws_appsync_path;
export default config;
